<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <Target Name="TailwindBuild" AfterTargets="TailwindBuildEvent">
	<Exec Command="npm run build:css" />
  </Target>

  <ItemGroup>
    <Compile Remove="Devices\**" />
    <Content Remove="Devices\**" />
    <EmbeddedResource Remove="Devices\**" />
    <None Remove="Devices\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AntDesign" Version="1.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Eclipse.eCAL.Core">
      <HintPath>bin\Debug\net10.0\Eclipse.eCAL.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DevicesConfig\" />
  </ItemGroup>

</Project>
